import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const font = Noto_Sans({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`bg-zinc-100 dark:bg-zinc-900 text-black dark:text-white ${font.className}`}
			>
				{children}
			</body>
		</html>
	);
}
